[build]
  command = "pip install -r requirements.txt"
  publish = "."
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.11"
  FLASK_APP = "app.py"
  FLASK_ENV = "production"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
  force = true

[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*" 