[build]
  command = "pip install -r requirements.txt"
  publish = "."

[build.environment]
  PYTHON_VERSION = "3.11"
  FLASK_APP = "app.py"
  FLASK_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200 