[build]
  command = "pip install -r requirements.txt && gunicorn app:app"
  publish = "."

[build.environment]
  PYTHON_VERSION = "3.11"
  FLASK_APP = "app.py"
  FLASK_ENV = "production"
  NODE_VERSION = "0"  # Disable Node.js

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 